os: Ubuntu
platform:
  - x64
install:
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  - sudo dpkg -i vagrant_2.2.9_x86_64.deb
  - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload vagrant-vbguest
  - git submodule init
  - git submodule update
build_script:
  - cp -v salt/roots/pillar/openfortivpn.sls.example salt/roots/pillar/openfortivpn.sls
  - sudo vagrant up --provider=libvirt openfortivpn-ubuntu1804
  - sudo vagrant ssh openfortivpn-ubuntu1804 -- sudo salt-call state.sls openfortivpn.package
  - sudo vagrant ssh openfortivpn-ubuntu1804 -- sudo salt-call state.sls openfortivpn.config
  - sudo vagrant ssh openfortivpn-ubuntu1804 -- sudo salt-call state.sls openfortivpn.config.clean
  - sudo vagrant ssh openfortivpn-ubuntu1804 -- sudo salt-call state.sls openfortivpn.package.clean
  - sudo vagrant destroy --force openfortivpn-ubuntu1804
test: off
